In [5]:
#dependencies
import pandas as pd
from sqlalchemy import create_engine

In [6]:
csv_file = "Happiness_by_country_2020.csv"
happiness_df = pd.read_csv(csv_file)
happiness_df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [10]:
population = "Population_by_Country_2020.csv"
population_df = pd.read_csv(population)
population_df.head()

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1438207241,0.39%,5540090,153,9388211,-348399.0,1.7,38,61%,18.47%
1,India,1377233523,0.99%,13586631,464,2973190,-532687.0,2.2,28,35%,17.70%
2,United States,330610570,0.59%,1937734,36,9147420,954806.0,1.8,38,83%,4.25%
3,Indonesia,272931713,1.07%,2898047,151,1811570,-98955.0,2.3,30,56%,3.51%
4,Pakistan,219992900,2.00%,4327022,287,770880,-233379.0,3.6,23,35%,2.83%

In [12]:
refined_happiness_df = happiness_df[["Country name", "Regional indicator", "Ladder score", "Logged GDP per capita", "Social support", "Perceptions of corruption"]]
refined_happiness_df.head()

,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Perceptions of corruption
0,Finland,Western Europe,7.8087,10.639267,0.954330,0.195445
1,Denmark,Western Europe,7.6456,10.774001,0.955991,0.168489
2,Switzerland,Western Europe,7.5599,10.979933,0.942847,0.303728
3,Iceland,Western Europe,7.5045,10.772559,0.974670,0.711710
4,Norway,Western Europe,7.4880,11.087804,0.952487,0.263218

In [15]:
refined_population_df = population_df [["Country (or dependency)", "Population (2020)", "Density (P/Km²)", "Land Area (Km²)", "Migrants (net)", "Urban Pop %"]]
refined_population_df.head()

,Country (or dependency),Population (2020),Density (P/Km²),Land Area (Km²),Migrants (net),Urban Pop %
0,China,1438207241,153,9388211,-348399.0,61%
1,India,1377233523,464,2973190,-532687.0,35%
2,United States,330610570,36,9147420,954806.0,83%
3,Indonesia,272931713,151,1811570,-98955.0,56%
4,Pakistan,219992900,287,770880,-233379.0,35%

In [16]:
refined_happiness_df["Country name"].value_counts()

Morocco       1
Lithuania     1
Libya         1
Belgium       1
Bulgaria      1
             ..
Kyrgyzstan    1
Sweden        1
Botswana      1
Nepal         1
Mali          1
Name: Country name, Length: 153, dtype: int64

In [18]:
refined_population_df["Country (or dependency)"].value_counts()

Curaçao       1
Malawi        1
Australia     1
Nauru         1
Uzbekistan    1
             ..
Moldova       1
Panama        1
Uganda        1
Liberia       1
Turkey        1
Name: Country (or dependency), Length: 235, dtype: int64